let parserModulePromise;
function installPdfRuntimeFallbacks() { if (!globalThis.DOMMatrix) globalThis.DOMMatrix = class DOMMatrix {}; if (!globalThis.ImageData) globalThis.ImageData = class ImageData {}; if (!globalThis.Path2D) globalThis.Path2D = class Path2D {}; }
export class PdfExtractionError extends Error { constructor(message = 'Unable to read document. Please upload a readable file.') { super(message); this.name = 'PdfExtractionError'; this.status = 400; } }
async function standardPdfText(buffer) { installPdfRuntimeFallbacks(); parserModulePromise ||= import('pdf-parse'); const { PDFParse } = await parserModulePromise; const parser = new PDFParse({ data: buffer }); try { return String((await parser.getText())?.text || '').replace(/\u0000/g, '').trim(); } finally { await parser.destroy(); } }
async function ocrPdf(buffer) {
  installPdfRuntimeFallbacks();
  const [{ getDocument }, { createCanvas }, { createWorker }] = await Promise.all([import('pdfjs-dist/legacy/build/pdf.mjs'), import('@napi-rs/canvas'), import('tesseract.js')]);
  const pdf = await getDocument({ data: new Uint8Array(buffer) }).promise; const worker = await createWorker('eng');
  try { const pages = []; for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber += 1) { const page = await pdf.getPage(pageNumber); const viewport = page.getViewport({ scale: 2 }); const canvas = createCanvas(Math.ceil(viewport.width), Math.ceil(viewport.height)); await page.render({ canvasContext: canvas.getContext('2d'), viewport }).promise; const { data } = await worker.recognize(canvas.toBuffer('image/png')); if (data?.text) pages.push(data.text); } return pages.join('\n\n').replace(/\u0000/g, '').trim(); } finally { await worker.terminate(); }
}
export async function extractPdfText(buffer) { if (!Buffer.isBuffer(buffer) || buffer.length === 0 || !buffer.subarray(0, 5).equals(Buffer.from('%PDF-'))) throw new PdfExtractionError('The PDF is corrupted or invalid.'); try { const text = await standardPdfText(buffer); if (text.length >= 20) return text; const ocrText = await ocrPdf(buffer); if (ocrText) return ocrText; throw new PdfExtractionError('The PDF contains no readable text.'); } catch (error) { if (error instanceof PdfExtractionError) throw error; throw new PdfExtractionError('The PDF is unreadable, encrypted, or corrupted.'); } }
export async function extractDocumentText(buffer, { filename = '', mimeType = '' } = {}) { if (!Buffer.isBuffer(buffer) || buffer.length === 0) throw new PdfExtractionError('The uploaded file is empty.'); const name = filename.toLowerCase(); try { if (name.endsWith('.pdf') || mimeType === 'application/pdf') return extractPdfText(buffer); if (name.endsWith('.docx') || mimeType.includes('wordprocessingml')) { const mammoth = await import('mammoth'); return String((await mammoth.extractRawText({ buffer })).value || '').trim(); } if (name.endsWith('.xlsx') || mimeType.includes('spreadsheetml')) { const XLSX = await import('xlsx'); const workbook = XLSX.read(buffer, { type: 'buffer' }); return workbook.SheetNames.map(sheet => XLSX.utils.sheet_to_csv(workbook.Sheets[sheet])).join('\n').trim(); } return buffer.toString('utf8').replace(/\u0000/g, '').trim(); } catch { throw new PdfExtractionError('The uploaded document could not be read.'); } }
